# Generated by Django 4.1.3 on 2022-11-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_pix'),
        ('home', '0005_product_slug'),
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('on delivery', 'on delivery'), ('With card', 'With card'), ('Online Payment', 'Online Payment')], default='on delivery', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profile')),
            ],
        ),
    ]
